Feature/wallet
517435708/simple_blockchain pull request #11
Opened 2020-10-23 14:15 UTC by BlaiseCz

2020-10-23 17:29 UTC, Krzysiulek commented on src/main/java/com/blackhearth/blockchain/wallet/BasicWalletFactory.java
> +public class BasicWalletFactory implements WalletFactory {
Zmień nazwę klasy bo to sugeruje, że jest to wzorzec fabryki, a ewidentnie nie jest:
https://javadeveloper.pl/wzorzec-projektowy-fabryka/

2020-10-23 17:29 UTC, Krzysiulek commented on src/main/java/com/blackhearth/blockchain/wallet/KeysGenerator.java
> +    }
@Getter

2020-10-23 17:29 UTC, Krzysiulek commented on src/main/java/com/blackhearth/blockchain/wallet/signature/SignatureUtils.java
> +    private SignatureUtils(){}
@NoArgsConstructor(access = PRIVATE)

2020-10-23 17:30 UTC, Krzysiulek commented on src/test/java/com/blackhearth/blockchain/wallet/signature/SignatureApplierTest.java
> +    }
uzupełnij albo wywal

2020-10-23 17:31 UTC, Krzysiulek commented on src/test/java/com/blackhearth/blockchain/wallet/signature/SignatureUtilsTest.java
> +
uzupełnij albo wywal. Ale może uzupełnij :D

2020-10-23 17:31 UTC, Krzysiulek commented on src/test/java/com/blackhearth/blockchain/wallet/signature/SignatureVerifierTest.java
> +    void verifySignature() {
Tosamo

2020-10-23 17:31 UTC, Krzysiulek commented on src/main/java/com/blackhearth/blockchain/wallet/signature/SignatureVerifier.java
> +    private SignatureVerifier(){}
@NoArgsConstructor(access = PRIVATE)

2020-10-23 18:19 UTC, 517435708 requested changes

2020-10-23 18:19 UTC, 517435708 commented on src/main/java/com/blackhearth/blockchain/wallet/BasicWalletService.java
> +    public String setWalletHash(Wallet wallet) {
get*

ta funkcja nic nie ustawia. lepsze słowo to calculate, a nazwa klasy to WalletHashCalculator, czy coś.

2020-10-23 18:19 UTC, 517435708 commented on src/main/java/com/blackhearth/blockchain/wallet/BasicWalletService.java
> +    public String setWalletHash(Wallet wallet) {
w sensie get albo calculate przy czym calculate jest lepsze.

2020-10-23 18:19 UTC, 517435708 commented on src/main/java/com/blackhearth/blockchain/wallet/BasicWalletService.java
> +public class BasicWalletService implements WalletService {
@Component, jedna instancja na całą aplikację.

2020-10-23 18:19 UTC, 517435708 commented on src/main/java/com/blackhearth/blockchain/wallet/signature/SignatureUtils.java
> +
tego fora można by nawet wywalić do innej funkcji, if statement zawsze z klamrami nawet jeśli masz do wykonania tylko jedną linijkę.

2020-10-23 18:19 UTC, 517435708 commented on src/main/java/com/blackhearth/blockchain/wallet/transaction/BasicTransactionService.java
> +public class BasicTransactionService implements TransactionService {
To samo co w WalletService

2020-10-23 18:19 UTC, 517435708 commented on src/test/java/com/blackhearth/blockchain/protocol/message/MessageFactoryTest.java
> +        transaction.setAmount((long) 12.12);
O_O!?

Wróć do Stringa, proszę....

2020-10-31 11:36 UTC, 517435708 approved these changes
Dla mnie ok

2020-10-31 11:37 UTC, 517435708 commented
Po rozwiązaniu konfliktów można mergować @Krzysiulek zaakceptuj mu pull requesta plz

2020-10-31 11:43 UTC, Krzysiulek approved these changes

2020-10-31 17:21 UTC, merged